security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH,ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        gettoken:
            pattern:  ^/api/open/getToken$
            stateless: true
            gfreeau_get_jwt:
                # this is the default config
                username_parameter: username
                password_parameter: password
                post_only: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: ze_user_security.authentication.handler.login_failure_handler

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


        api:
            pattern:    ^/api/secure/*
            stateless:  true
            lexik_jwt:
                authorization_header: # check token in Authorization Header
                    enabled: true
                    prefix:  Bearer
                throw_exceptions:        true     # When an authentication failure occurs, return a 401 response immediately
                create_entry_point:      true      # When no authentication details are provided, create a default entry point that returns a 401 response

    access_control:
        - { path: ^/api/open/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/secure/*, roles: [ IS_AUTHENTICATED_FULLY ] }
